/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_appsync_graphqlEndpoint:
    "https://7tj25x3fajdunixykrf6eekttu.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_appsync_apiKey: "da2-4iycnvjpnnch3nbkxqidp3wasu",
  aws_cognito_identity_pool_id:
    "us-east-1:9da7b4d6-e08a-4477-9005-283b77701118",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_dFgVhNO5B",
  aws_user_pools_web_client_id: "5rnpoh19kg3qv2dtja311vol51",
  oauth: {
    domain:
      "reciperealmapp22641020-22641020-dev.auth.us-east-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "exp://127.0.0.1:19000/--/",
    redirectSignOut: "exp://127.0.0.1:19000/--/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_user_files_s3_bucket:
    "reciperealmappfd2a389fb7b44050849732c2848ad156211534-dev",
  aws_user_files_s3_bucket_region: "us-east-1",
  aws_mobile_analytics_app_id: "9d4e099f73e74551a32df97de6fb6b8d",
  aws_mobile_analytics_app_region: "us-east-1",
  Analytics: {
    AWSPinpoint: {
      appId: "9d4e099f73e74551a32df97de6fb6b8d",
      region: "us-east-1",
    },
  },
};

export default awsmobile;
